//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.pedido_cabecalho = new HashSet<pedido_cabecalho>();
        }
    
        public int idcliente { get; set; }
        public string nome { get; set; }
        public string cpf_cnpj { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string cep { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string status_cliente { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
    
        public virtual ICollection<pedido_cabecalho> pedido_cabecalho { get; set; }
    }
}
