//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoDadosEntities : DbContext
    {
        public BancoDadosEntities()
            : base("name=BancoDadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<pedido_cabecalho> pedido_cabecalho { get; set; }
        public virtual DbSet<pedido_itens> pedido_itens { get; set; }
        public virtual DbSet<produto> produto { get; set; }
    }
}
