//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_itens
    {
        public int idpedido_itens { get; set; }
        public int idpedido_cabecalho { get; set; }
        public int idproduto { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<decimal> valor_unitario { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public string status_item { get; set; }
    
        public virtual pedido_cabecalho pedido_cabecalho { get; set; }
        public virtual produto produto { get; set; }
    }
}
