//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.pedido_itens = new HashSet<pedido_itens>();
        }
    
        public int idproduto { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> preco_compra { get; set; }
        public Nullable<decimal> preco_venda { get; set; }
        public Nullable<int> qtde_estoque { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string status_produto { get; set; }
    
        public virtual ICollection<pedido_itens> pedido_itens { get; set; }
    }
}
